### ISSUE TITLE
Unable to join Slack Community

### ISSUE THREAD

**Issue by vazquev** [r4ds/r4ds_app#27]
Hello,

I keep getting a link expired error when trying to join your slack community.

Thank you,

Vince

**Comment by jonthegeek** [comment]
Thank you for letting us know! The link is *supposed* to never expire, but Slack randomly expires the link from time to time. It should work now! If it doesn't work right away, wait a while and try again (it might take a while for the update to propagate to you)

https://r4ds.io/join
